/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package br.com.cnf.curso.inscricao.model.impl;

import br.com.cnf.curso.inscricao.model.CursoParticipante;
import br.com.cnf.curso.inscricao.service.CursoParticipanteLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the CursoParticipante service. Represents a row in the &quot;cnf_CursoParticipante&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CursoParticipanteImpl}.
 * </p>
 *
 * @author SEA
 * @see CursoParticipanteImpl
 * @see br.com.cnf.curso.inscricao.model.CursoParticipante
 * @generated
 */
public abstract class CursoParticipanteBaseImpl
	extends CursoParticipanteModelImpl implements CursoParticipante {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a curso participante model instance should use the {@link CursoParticipante} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			CursoParticipanteLocalServiceUtil.addCursoParticipante(this);
		}
		else {
			CursoParticipanteLocalServiceUtil.updateCursoParticipante(this);
		}
	}
}