/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package br.com.cnf.curso.inscricao.model.impl;

import br.com.cnf.curso.inscricao.model.CursoInscricao;
import br.com.cnf.curso.inscricao.service.CursoInscricaoLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the CursoInscricao service. Represents a row in the &quot;cnf_CursoInscricao&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CursoInscricaoImpl}.
 * </p>
 *
 * @author SEA
 * @see CursoInscricaoImpl
 * @see br.com.cnf.curso.inscricao.model.CursoInscricao
 * @generated
 */
public abstract class CursoInscricaoBaseImpl extends CursoInscricaoModelImpl
	implements CursoInscricao {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a curso inscricao model instance should use the {@link CursoInscricao} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			CursoInscricaoLocalServiceUtil.addCursoInscricao(this);
		}
		else {
			CursoInscricaoLocalServiceUtil.updateCursoInscricao(this);
		}
	}
}