/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package br.com.cnf.curso.inscricao.model.impl;

import br.com.cnf.curso.inscricao.model.CursoInscricaoCnpj;
import br.com.cnf.curso.inscricao.model.CursoInscricaoCnpjModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the CursoInscricaoCnpj service. Represents a row in the &quot;cnf_CursoInscricaoCnpj&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link br.com.cnf.curso.inscricao.model.CursoInscricaoCnpjModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CursoInscricaoCnpjImpl}.
 * </p>
 *
 * @author SEA
 * @see CursoInscricaoCnpjImpl
 * @see br.com.cnf.curso.inscricao.model.CursoInscricaoCnpj
 * @see br.com.cnf.curso.inscricao.model.CursoInscricaoCnpjModel
 * @generated
 */
public class CursoInscricaoCnpjModelImpl extends BaseModelImpl<CursoInscricaoCnpj>
	implements CursoInscricaoCnpjModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a curso inscricao cnpj model instance should use the {@link br.com.cnf.curso.inscricao.model.CursoInscricaoCnpj} interface instead.
	 */
	public static final String TABLE_NAME = "cnf_CursoInscricaoCnpj";
	public static final Object[][] TABLE_COLUMNS = {
			{ "inscricaoCnpjId", Types.BIGINT },
			{ "inscricaoId", Types.BIGINT },
			{ "razaoSocial", Types.VARCHAR },
			{ "nomeFantasia", Types.VARCHAR },
			{ "inscricaoEstadual", Types.VARCHAR },
			{ "endereco", Types.VARCHAR },
			{ "bairro", Types.VARCHAR },
			{ "cidade", Types.VARCHAR },
			{ "estado", Types.VARCHAR },
			{ "cep", Types.VARCHAR },
			{ "dddTelefone", Types.VARCHAR },
			{ "telefone", Types.VARCHAR },
			{ "nfNome", Types.VARCHAR },
			{ "nfDepartamento", Types.VARCHAR },
			{ "nfEmail", Types.VARCHAR },
			{ "nfDddTelefone", Types.VARCHAR },
			{ "nfTelefone", Types.VARCHAR },
			{ "observacao", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table cnf_CursoInscricaoCnpj (inscricaoCnpjId LONG not null primary key,inscricaoId LONG,razaoSocial VARCHAR(300) null,nomeFantasia VARCHAR(300) null,inscricaoEstadual VARCHAR(75) null,endereco VARCHAR(300) null,bairro VARCHAR(75) null,cidade VARCHAR(75) null,estado VARCHAR(75) null,cep VARCHAR(75) null,dddTelefone VARCHAR(2) null,telefone VARCHAR(10) null,nfNome VARCHAR(300) null,nfDepartamento VARCHAR(75) null,nfEmail VARCHAR(300) null,nfDddTelefone VARCHAR(2) null,nfTelefone VARCHAR(10) null,observacao VARCHAR(1000) null)";
	public static final String TABLE_SQL_DROP = "drop table cnf_CursoInscricaoCnpj";
	public static final String ORDER_BY_JPQL = " ORDER BY cursoInscricaoCnpj.razaoSocial ASC";
	public static final String ORDER_BY_SQL = " ORDER BY cnf_CursoInscricaoCnpj.razaoSocial ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.br.com.cnf.curso.inscricao.model.CursoInscricaoCnpj"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.br.com.cnf.curso.inscricao.model.CursoInscricaoCnpj"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.br.com.cnf.curso.inscricao.model.CursoInscricaoCnpj"));

	public CursoInscricaoCnpjModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _inscricaoCnpjId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setInscricaoCnpjId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _inscricaoCnpjId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CursoInscricaoCnpj.class;
	}

	@Override
	public String getModelClassName() {
		return CursoInscricaoCnpj.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("inscricaoCnpjId", getInscricaoCnpjId());
		attributes.put("inscricaoId", getInscricaoId());
		attributes.put("razaoSocial", getRazaoSocial());
		attributes.put("nomeFantasia", getNomeFantasia());
		attributes.put("inscricaoEstadual", getInscricaoEstadual());
		attributes.put("endereco", getEndereco());
		attributes.put("bairro", getBairro());
		attributes.put("cidade", getCidade());
		attributes.put("estado", getEstado());
		attributes.put("cep", getCep());
		attributes.put("dddTelefone", getDddTelefone());
		attributes.put("telefone", getTelefone());
		attributes.put("nfNome", getNfNome());
		attributes.put("nfDepartamento", getNfDepartamento());
		attributes.put("nfEmail", getNfEmail());
		attributes.put("nfDddTelefone", getNfDddTelefone());
		attributes.put("nfTelefone", getNfTelefone());
		attributes.put("observacao", getObservacao());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long inscricaoCnpjId = (Long)attributes.get("inscricaoCnpjId");

		if (inscricaoCnpjId != null) {
			setInscricaoCnpjId(inscricaoCnpjId);
		}

		Long inscricaoId = (Long)attributes.get("inscricaoId");

		if (inscricaoId != null) {
			setInscricaoId(inscricaoId);
		}

		String razaoSocial = (String)attributes.get("razaoSocial");

		if (razaoSocial != null) {
			setRazaoSocial(razaoSocial);
		}

		String nomeFantasia = (String)attributes.get("nomeFantasia");

		if (nomeFantasia != null) {
			setNomeFantasia(nomeFantasia);
		}

		String inscricaoEstadual = (String)attributes.get("inscricaoEstadual");

		if (inscricaoEstadual != null) {
			setInscricaoEstadual(inscricaoEstadual);
		}

		String endereco = (String)attributes.get("endereco");

		if (endereco != null) {
			setEndereco(endereco);
		}

		String bairro = (String)attributes.get("bairro");

		if (bairro != null) {
			setBairro(bairro);
		}

		String cidade = (String)attributes.get("cidade");

		if (cidade != null) {
			setCidade(cidade);
		}

		String estado = (String)attributes.get("estado");

		if (estado != null) {
			setEstado(estado);
		}

		String cep = (String)attributes.get("cep");

		if (cep != null) {
			setCep(cep);
		}

		String dddTelefone = (String)attributes.get("dddTelefone");

		if (dddTelefone != null) {
			setDddTelefone(dddTelefone);
		}

		String telefone = (String)attributes.get("telefone");

		if (telefone != null) {
			setTelefone(telefone);
		}

		String nfNome = (String)attributes.get("nfNome");

		if (nfNome != null) {
			setNfNome(nfNome);
		}

		String nfDepartamento = (String)attributes.get("nfDepartamento");

		if (nfDepartamento != null) {
			setNfDepartamento(nfDepartamento);
		}

		String nfEmail = (String)attributes.get("nfEmail");

		if (nfEmail != null) {
			setNfEmail(nfEmail);
		}

		String nfDddTelefone = (String)attributes.get("nfDddTelefone");

		if (nfDddTelefone != null) {
			setNfDddTelefone(nfDddTelefone);
		}

		String nfTelefone = (String)attributes.get("nfTelefone");

		if (nfTelefone != null) {
			setNfTelefone(nfTelefone);
		}

		String observacao = (String)attributes.get("observacao");

		if (observacao != null) {
			setObservacao(observacao);
		}
	}

	@Override
	public long getInscricaoCnpjId() {
		return _inscricaoCnpjId;
	}

	@Override
	public void setInscricaoCnpjId(long inscricaoCnpjId) {
		_inscricaoCnpjId = inscricaoCnpjId;
	}

	@Override
	public long getInscricaoId() {
		return _inscricaoId;
	}

	@Override
	public void setInscricaoId(long inscricaoId) {
		_inscricaoId = inscricaoId;
	}

	@Override
	public String getRazaoSocial() {
		if (_razaoSocial == null) {
			return StringPool.BLANK;
		}
		else {
			return _razaoSocial;
		}
	}

	@Override
	public void setRazaoSocial(String razaoSocial) {
		_razaoSocial = razaoSocial;
	}

	@Override
	public String getNomeFantasia() {
		if (_nomeFantasia == null) {
			return StringPool.BLANK;
		}
		else {
			return _nomeFantasia;
		}
	}

	@Override
	public void setNomeFantasia(String nomeFantasia) {
		_nomeFantasia = nomeFantasia;
	}

	@Override
	public String getInscricaoEstadual() {
		if (_inscricaoEstadual == null) {
			return StringPool.BLANK;
		}
		else {
			return _inscricaoEstadual;
		}
	}

	@Override
	public void setInscricaoEstadual(String inscricaoEstadual) {
		_inscricaoEstadual = inscricaoEstadual;
	}

	@Override
	public String getEndereco() {
		if (_endereco == null) {
			return StringPool.BLANK;
		}
		else {
			return _endereco;
		}
	}

	@Override
	public void setEndereco(String endereco) {
		_endereco = endereco;
	}

	@Override
	public String getBairro() {
		if (_bairro == null) {
			return StringPool.BLANK;
		}
		else {
			return _bairro;
		}
	}

	@Override
	public void setBairro(String bairro) {
		_bairro = bairro;
	}

	@Override
	public String getCidade() {
		if (_cidade == null) {
			return StringPool.BLANK;
		}
		else {
			return _cidade;
		}
	}

	@Override
	public void setCidade(String cidade) {
		_cidade = cidade;
	}

	@Override
	public String getEstado() {
		if (_estado == null) {
			return StringPool.BLANK;
		}
		else {
			return _estado;
		}
	}

	@Override
	public void setEstado(String estado) {
		_estado = estado;
	}

	@Override
	public String getCep() {
		if (_cep == null) {
			return StringPool.BLANK;
		}
		else {
			return _cep;
		}
	}

	@Override
	public void setCep(String cep) {
		_cep = cep;
	}

	@Override
	public String getDddTelefone() {
		if (_dddTelefone == null) {
			return StringPool.BLANK;
		}
		else {
			return _dddTelefone;
		}
	}

	@Override
	public void setDddTelefone(String dddTelefone) {
		_dddTelefone = dddTelefone;
	}

	@Override
	public String getTelefone() {
		if (_telefone == null) {
			return StringPool.BLANK;
		}
		else {
			return _telefone;
		}
	}

	@Override
	public void setTelefone(String telefone) {
		_telefone = telefone;
	}

	@Override
	public String getNfNome() {
		if (_nfNome == null) {
			return StringPool.BLANK;
		}
		else {
			return _nfNome;
		}
	}

	@Override
	public void setNfNome(String nfNome) {
		_nfNome = nfNome;
	}

	@Override
	public String getNfDepartamento() {
		if (_nfDepartamento == null) {
			return StringPool.BLANK;
		}
		else {
			return _nfDepartamento;
		}
	}

	@Override
	public void setNfDepartamento(String nfDepartamento) {
		_nfDepartamento = nfDepartamento;
	}

	@Override
	public String getNfEmail() {
		if (_nfEmail == null) {
			return StringPool.BLANK;
		}
		else {
			return _nfEmail;
		}
	}

	@Override
	public void setNfEmail(String nfEmail) {
		_nfEmail = nfEmail;
	}

	@Override
	public String getNfDddTelefone() {
		if (_nfDddTelefone == null) {
			return StringPool.BLANK;
		}
		else {
			return _nfDddTelefone;
		}
	}

	@Override
	public void setNfDddTelefone(String nfDddTelefone) {
		_nfDddTelefone = nfDddTelefone;
	}

	@Override
	public String getNfTelefone() {
		if (_nfTelefone == null) {
			return StringPool.BLANK;
		}
		else {
			return _nfTelefone;
		}
	}

	@Override
	public void setNfTelefone(String nfTelefone) {
		_nfTelefone = nfTelefone;
	}

	@Override
	public String getObservacao() {
		if (_observacao == null) {
			return StringPool.BLANK;
		}
		else {
			return _observacao;
		}
	}

	@Override
	public void setObservacao(String observacao) {
		_observacao = observacao;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			CursoInscricaoCnpj.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CursoInscricaoCnpj toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (CursoInscricaoCnpj)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CursoInscricaoCnpjImpl cursoInscricaoCnpjImpl = new CursoInscricaoCnpjImpl();

		cursoInscricaoCnpjImpl.setInscricaoCnpjId(getInscricaoCnpjId());
		cursoInscricaoCnpjImpl.setInscricaoId(getInscricaoId());
		cursoInscricaoCnpjImpl.setRazaoSocial(getRazaoSocial());
		cursoInscricaoCnpjImpl.setNomeFantasia(getNomeFantasia());
		cursoInscricaoCnpjImpl.setInscricaoEstadual(getInscricaoEstadual());
		cursoInscricaoCnpjImpl.setEndereco(getEndereco());
		cursoInscricaoCnpjImpl.setBairro(getBairro());
		cursoInscricaoCnpjImpl.setCidade(getCidade());
		cursoInscricaoCnpjImpl.setEstado(getEstado());
		cursoInscricaoCnpjImpl.setCep(getCep());
		cursoInscricaoCnpjImpl.setDddTelefone(getDddTelefone());
		cursoInscricaoCnpjImpl.setTelefone(getTelefone());
		cursoInscricaoCnpjImpl.setNfNome(getNfNome());
		cursoInscricaoCnpjImpl.setNfDepartamento(getNfDepartamento());
		cursoInscricaoCnpjImpl.setNfEmail(getNfEmail());
		cursoInscricaoCnpjImpl.setNfDddTelefone(getNfDddTelefone());
		cursoInscricaoCnpjImpl.setNfTelefone(getNfTelefone());
		cursoInscricaoCnpjImpl.setObservacao(getObservacao());

		cursoInscricaoCnpjImpl.resetOriginalValues();

		return cursoInscricaoCnpjImpl;
	}

	@Override
	public int compareTo(CursoInscricaoCnpj cursoInscricaoCnpj) {
		int value = 0;

		value = getRazaoSocial().compareTo(cursoInscricaoCnpj.getRazaoSocial());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CursoInscricaoCnpj)) {
			return false;
		}

		CursoInscricaoCnpj cursoInscricaoCnpj = (CursoInscricaoCnpj)obj;

		long primaryKey = cursoInscricaoCnpj.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<CursoInscricaoCnpj> toCacheModel() {
		CursoInscricaoCnpjCacheModel cursoInscricaoCnpjCacheModel = new CursoInscricaoCnpjCacheModel();

		cursoInscricaoCnpjCacheModel.inscricaoCnpjId = getInscricaoCnpjId();

		cursoInscricaoCnpjCacheModel.inscricaoId = getInscricaoId();

		cursoInscricaoCnpjCacheModel.razaoSocial = getRazaoSocial();

		String razaoSocial = cursoInscricaoCnpjCacheModel.razaoSocial;

		if ((razaoSocial != null) && (razaoSocial.length() == 0)) {
			cursoInscricaoCnpjCacheModel.razaoSocial = null;
		}

		cursoInscricaoCnpjCacheModel.nomeFantasia = getNomeFantasia();

		String nomeFantasia = cursoInscricaoCnpjCacheModel.nomeFantasia;

		if ((nomeFantasia != null) && (nomeFantasia.length() == 0)) {
			cursoInscricaoCnpjCacheModel.nomeFantasia = null;
		}

		cursoInscricaoCnpjCacheModel.inscricaoEstadual = getInscricaoEstadual();

		String inscricaoEstadual = cursoInscricaoCnpjCacheModel.inscricaoEstadual;

		if ((inscricaoEstadual != null) && (inscricaoEstadual.length() == 0)) {
			cursoInscricaoCnpjCacheModel.inscricaoEstadual = null;
		}

		cursoInscricaoCnpjCacheModel.endereco = getEndereco();

		String endereco = cursoInscricaoCnpjCacheModel.endereco;

		if ((endereco != null) && (endereco.length() == 0)) {
			cursoInscricaoCnpjCacheModel.endereco = null;
		}

		cursoInscricaoCnpjCacheModel.bairro = getBairro();

		String bairro = cursoInscricaoCnpjCacheModel.bairro;

		if ((bairro != null) && (bairro.length() == 0)) {
			cursoInscricaoCnpjCacheModel.bairro = null;
		}

		cursoInscricaoCnpjCacheModel.cidade = getCidade();

		String cidade = cursoInscricaoCnpjCacheModel.cidade;

		if ((cidade != null) && (cidade.length() == 0)) {
			cursoInscricaoCnpjCacheModel.cidade = null;
		}

		cursoInscricaoCnpjCacheModel.estado = getEstado();

		String estado = cursoInscricaoCnpjCacheModel.estado;

		if ((estado != null) && (estado.length() == 0)) {
			cursoInscricaoCnpjCacheModel.estado = null;
		}

		cursoInscricaoCnpjCacheModel.cep = getCep();

		String cep = cursoInscricaoCnpjCacheModel.cep;

		if ((cep != null) && (cep.length() == 0)) {
			cursoInscricaoCnpjCacheModel.cep = null;
		}

		cursoInscricaoCnpjCacheModel.dddTelefone = getDddTelefone();

		String dddTelefone = cursoInscricaoCnpjCacheModel.dddTelefone;

		if ((dddTelefone != null) && (dddTelefone.length() == 0)) {
			cursoInscricaoCnpjCacheModel.dddTelefone = null;
		}

		cursoInscricaoCnpjCacheModel.telefone = getTelefone();

		String telefone = cursoInscricaoCnpjCacheModel.telefone;

		if ((telefone != null) && (telefone.length() == 0)) {
			cursoInscricaoCnpjCacheModel.telefone = null;
		}

		cursoInscricaoCnpjCacheModel.nfNome = getNfNome();

		String nfNome = cursoInscricaoCnpjCacheModel.nfNome;

		if ((nfNome != null) && (nfNome.length() == 0)) {
			cursoInscricaoCnpjCacheModel.nfNome = null;
		}

		cursoInscricaoCnpjCacheModel.nfDepartamento = getNfDepartamento();

		String nfDepartamento = cursoInscricaoCnpjCacheModel.nfDepartamento;

		if ((nfDepartamento != null) && (nfDepartamento.length() == 0)) {
			cursoInscricaoCnpjCacheModel.nfDepartamento = null;
		}

		cursoInscricaoCnpjCacheModel.nfEmail = getNfEmail();

		String nfEmail = cursoInscricaoCnpjCacheModel.nfEmail;

		if ((nfEmail != null) && (nfEmail.length() == 0)) {
			cursoInscricaoCnpjCacheModel.nfEmail = null;
		}

		cursoInscricaoCnpjCacheModel.nfDddTelefone = getNfDddTelefone();

		String nfDddTelefone = cursoInscricaoCnpjCacheModel.nfDddTelefone;

		if ((nfDddTelefone != null) && (nfDddTelefone.length() == 0)) {
			cursoInscricaoCnpjCacheModel.nfDddTelefone = null;
		}

		cursoInscricaoCnpjCacheModel.nfTelefone = getNfTelefone();

		String nfTelefone = cursoInscricaoCnpjCacheModel.nfTelefone;

		if ((nfTelefone != null) && (nfTelefone.length() == 0)) {
			cursoInscricaoCnpjCacheModel.nfTelefone = null;
		}

		cursoInscricaoCnpjCacheModel.observacao = getObservacao();

		String observacao = cursoInscricaoCnpjCacheModel.observacao;

		if ((observacao != null) && (observacao.length() == 0)) {
			cursoInscricaoCnpjCacheModel.observacao = null;
		}

		return cursoInscricaoCnpjCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(37);

		sb.append("{inscricaoCnpjId=");
		sb.append(getInscricaoCnpjId());
		sb.append(", inscricaoId=");
		sb.append(getInscricaoId());
		sb.append(", razaoSocial=");
		sb.append(getRazaoSocial());
		sb.append(", nomeFantasia=");
		sb.append(getNomeFantasia());
		sb.append(", inscricaoEstadual=");
		sb.append(getInscricaoEstadual());
		sb.append(", endereco=");
		sb.append(getEndereco());
		sb.append(", bairro=");
		sb.append(getBairro());
		sb.append(", cidade=");
		sb.append(getCidade());
		sb.append(", estado=");
		sb.append(getEstado());
		sb.append(", cep=");
		sb.append(getCep());
		sb.append(", dddTelefone=");
		sb.append(getDddTelefone());
		sb.append(", telefone=");
		sb.append(getTelefone());
		sb.append(", nfNome=");
		sb.append(getNfNome());
		sb.append(", nfDepartamento=");
		sb.append(getNfDepartamento());
		sb.append(", nfEmail=");
		sb.append(getNfEmail());
		sb.append(", nfDddTelefone=");
		sb.append(getNfDddTelefone());
		sb.append(", nfTelefone=");
		sb.append(getNfTelefone());
		sb.append(", observacao=");
		sb.append(getObservacao());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(58);

		sb.append("<model><model-name>");
		sb.append("br.com.cnf.curso.inscricao.model.CursoInscricaoCnpj");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>inscricaoCnpjId</column-name><column-value><![CDATA[");
		sb.append(getInscricaoCnpjId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>inscricaoId</column-name><column-value><![CDATA[");
		sb.append(getInscricaoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>razaoSocial</column-name><column-value><![CDATA[");
		sb.append(getRazaoSocial());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nomeFantasia</column-name><column-value><![CDATA[");
		sb.append(getNomeFantasia());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>inscricaoEstadual</column-name><column-value><![CDATA[");
		sb.append(getInscricaoEstadual());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endereco</column-name><column-value><![CDATA[");
		sb.append(getEndereco());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>bairro</column-name><column-value><![CDATA[");
		sb.append(getBairro());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cidade</column-name><column-value><![CDATA[");
		sb.append(getCidade());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>estado</column-name><column-value><![CDATA[");
		sb.append(getEstado());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cep</column-name><column-value><![CDATA[");
		sb.append(getCep());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dddTelefone</column-name><column-value><![CDATA[");
		sb.append(getDddTelefone());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>telefone</column-name><column-value><![CDATA[");
		sb.append(getTelefone());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nfNome</column-name><column-value><![CDATA[");
		sb.append(getNfNome());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nfDepartamento</column-name><column-value><![CDATA[");
		sb.append(getNfDepartamento());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nfEmail</column-name><column-value><![CDATA[");
		sb.append(getNfEmail());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nfDddTelefone</column-name><column-value><![CDATA[");
		sb.append(getNfDddTelefone());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nfTelefone</column-name><column-value><![CDATA[");
		sb.append(getNfTelefone());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>observacao</column-name><column-value><![CDATA[");
		sb.append(getObservacao());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = CursoInscricaoCnpj.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			CursoInscricaoCnpj.class
		};
	private long _inscricaoCnpjId;
	private long _inscricaoId;
	private String _razaoSocial;
	private String _nomeFantasia;
	private String _inscricaoEstadual;
	private String _endereco;
	private String _bairro;
	private String _cidade;
	private String _estado;
	private String _cep;
	private String _dddTelefone;
	private String _telefone;
	private String _nfNome;
	private String _nfDepartamento;
	private String _nfEmail;
	private String _nfDddTelefone;
	private String _nfTelefone;
	private String _observacao;
	private CursoInscricaoCnpj _escapedModel;
}