/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package br.com.cnf.curso.inscricao.model.impl;

import br.com.cnf.curso.inscricao.model.CursoInscricaoCnpj;
import br.com.cnf.curso.inscricao.service.CursoInscricaoCnpjLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the CursoInscricaoCnpj service. Represents a row in the &quot;cnf_CursoInscricaoCnpj&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CursoInscricaoCnpjImpl}.
 * </p>
 *
 * @author SEA
 * @see CursoInscricaoCnpjImpl
 * @see br.com.cnf.curso.inscricao.model.CursoInscricaoCnpj
 * @generated
 */
public abstract class CursoInscricaoCnpjBaseImpl
	extends CursoInscricaoCnpjModelImpl implements CursoInscricaoCnpj {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a curso inscricao cnpj model instance should use the {@link CursoInscricaoCnpj} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			CursoInscricaoCnpjLocalServiceUtil.addCursoInscricaoCnpj(this);
		}
		else {
			CursoInscricaoCnpjLocalServiceUtil.updateCursoInscricaoCnpj(this);
		}
	}
}