/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package br.com.cnf.curso.inscricao.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the CursoParticipante service. Represents a row in the &quot;cnf_CursoParticipante&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link br.com.cnf.curso.inscricao.model.impl.CursoParticipanteModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link br.com.cnf.curso.inscricao.model.impl.CursoParticipanteImpl}.
 * </p>
 *
 * @author SEA
 * @see CursoParticipante
 * @see br.com.cnf.curso.inscricao.model.impl.CursoParticipanteImpl
 * @see br.com.cnf.curso.inscricao.model.impl.CursoParticipanteModelImpl
 * @generated
 */
public interface CursoParticipanteModel extends BaseModel<CursoParticipante> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a curso participante model instance should use the {@link CursoParticipante} interface instead.
	 */

	/**
	 * Returns the primary key of this curso participante.
	 *
	 * @return the primary key of this curso participante
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this curso participante.
	 *
	 * @param primaryKey the primary key of this curso participante
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the participante ID of this curso participante.
	 *
	 * @return the participante ID of this curso participante
	 */
	public long getParticipanteId();

	/**
	 * Sets the participante ID of this curso participante.
	 *
	 * @param participanteId the participante ID of this curso participante
	 */
	public void setParticipanteId(long participanteId);

	/**
	 * Returns the inscricao ID of this curso participante.
	 *
	 * @return the inscricao ID of this curso participante
	 */
	public long getInscricaoId();

	/**
	 * Sets the inscricao ID of this curso participante.
	 *
	 * @param inscricaoId the inscricao ID of this curso participante
	 */
	public void setInscricaoId(long inscricaoId);

	/**
	 * Returns the nome completo of this curso participante.
	 *
	 * @return the nome completo of this curso participante
	 */
	@AutoEscape
	public String getNomeCompleto();

	/**
	 * Sets the nome completo of this curso participante.
	 *
	 * @param nomeCompleto the nome completo of this curso participante
	 */
	public void setNomeCompleto(String nomeCompleto);

	/**
	 * Returns the nome cracha of this curso participante.
	 *
	 * @return the nome cracha of this curso participante
	 */
	@AutoEscape
	public String getNomeCracha();

	/**
	 * Sets the nome cracha of this curso participante.
	 *
	 * @param nomeCracha the nome cracha of this curso participante
	 */
	public void setNomeCracha(String nomeCracha);

	/**
	 * Returns the cpf of this curso participante.
	 *
	 * @return the cpf of this curso participante
	 */
	@AutoEscape
	public String getCpf();

	/**
	 * Sets the cpf of this curso participante.
	 *
	 * @param cpf the cpf of this curso participante
	 */
	public void setCpf(String cpf);

	/**
	 * Returns the sexo of this curso participante.
	 *
	 * @return the sexo of this curso participante
	 */
	@AutoEscape
	public String getSexo();

	/**
	 * Sets the sexo of this curso participante.
	 *
	 * @param sexo the sexo of this curso participante
	 */
	public void setSexo(String sexo);

	/**
	 * Returns the cargo of this curso participante.
	 *
	 * @return the cargo of this curso participante
	 */
	@AutoEscape
	public String getCargo();

	/**
	 * Sets the cargo of this curso participante.
	 *
	 * @param cargo the cargo of this curso participante
	 */
	public void setCargo(String cargo);

	/**
	 * Returns the empresa onde trabalha of this curso participante.
	 *
	 * @return the empresa onde trabalha of this curso participante
	 */
	@AutoEscape
	public String getEmpresaOndeTrabalha();

	/**
	 * Sets the empresa onde trabalha of this curso participante.
	 *
	 * @param empresaOndeTrabalha the empresa onde trabalha of this curso participante
	 */
	public void setEmpresaOndeTrabalha(String empresaOndeTrabalha);

	/**
	 * Returns the departamento of this curso participante.
	 *
	 * @return the departamento of this curso participante
	 */
	@AutoEscape
	public String getDepartamento();

	/**
	 * Sets the departamento of this curso participante.
	 *
	 * @param departamento the departamento of this curso participante
	 */
	public void setDepartamento(String departamento);

	/**
	 * Returns the formacao academica of this curso participante.
	 *
	 * @return the formacao academica of this curso participante
	 */
	@AutoEscape
	public String getFormacaoAcademica();

	/**
	 * Sets the formacao academica of this curso participante.
	 *
	 * @param formacaoAcademica the formacao academica of this curso participante
	 */
	public void setFormacaoAcademica(String formacaoAcademica);

	/**
	 * Returns the email principal of this curso participante.
	 *
	 * @return the email principal of this curso participante
	 */
	@AutoEscape
	public String getEmailPrincipal();

	/**
	 * Sets the email principal of this curso participante.
	 *
	 * @param emailPrincipal the email principal of this curso participante
	 */
	public void setEmailPrincipal(String emailPrincipal);

	/**
	 * Returns the email opcional of this curso participante.
	 *
	 * @return the email opcional of this curso participante
	 */
	@AutoEscape
	public String getEmailOpcional();

	/**
	 * Sets the email opcional of this curso participante.
	 *
	 * @param emailOpcional the email opcional of this curso participante
	 */
	public void setEmailOpcional(String emailOpcional);

	/**
	 * Returns the ddd telefone comercial of this curso participante.
	 *
	 * @return the ddd telefone comercial of this curso participante
	 */
	@AutoEscape
	public String getDddTelefoneComercial();

	/**
	 * Sets the ddd telefone comercial of this curso participante.
	 *
	 * @param dddTelefoneComercial the ddd telefone comercial of this curso participante
	 */
	public void setDddTelefoneComercial(String dddTelefoneComercial);

	/**
	 * Returns the telefone comercial of this curso participante.
	 *
	 * @return the telefone comercial of this curso participante
	 */
	@AutoEscape
	public String getTelefoneComercial();

	/**
	 * Sets the telefone comercial of this curso participante.
	 *
	 * @param telefoneComercial the telefone comercial of this curso participante
	 */
	public void setTelefoneComercial(String telefoneComercial);

	/**
	 * Returns the ddd telefone pessoal of this curso participante.
	 *
	 * @return the ddd telefone pessoal of this curso participante
	 */
	@AutoEscape
	public String getDddTelefonePessoal();

	/**
	 * Sets the ddd telefone pessoal of this curso participante.
	 *
	 * @param dddTelefonePessoal the ddd telefone pessoal of this curso participante
	 */
	public void setDddTelefonePessoal(String dddTelefonePessoal);

	/**
	 * Returns the telefone pessoal of this curso participante.
	 *
	 * @return the telefone pessoal of this curso participante
	 */
	@AutoEscape
	public String getTelefonePessoal();

	/**
	 * Sets the telefone pessoal of this curso participante.
	 *
	 * @param telefonePessoal the telefone pessoal of this curso participante
	 */
	public void setTelefonePessoal(String telefonePessoal);

	/**
	 * Returns the ddd telefone celular of this curso participante.
	 *
	 * @return the ddd telefone celular of this curso participante
	 */
	@AutoEscape
	public String getDddTelefoneCelular();

	/**
	 * Sets the ddd telefone celular of this curso participante.
	 *
	 * @param dddTelefoneCelular the ddd telefone celular of this curso participante
	 */
	public void setDddTelefoneCelular(String dddTelefoneCelular);

	/**
	 * Returns the telefone celular of this curso participante.
	 *
	 * @return the telefone celular of this curso participante
	 */
	@AutoEscape
	public String getTelefoneCelular();

	/**
	 * Sets the telefone celular of this curso participante.
	 *
	 * @param telefoneCelular the telefone celular of this curso participante
	 */
	public void setTelefoneCelular(String telefoneCelular);

	/**
	 * Returns the endereco of this curso participante.
	 *
	 * @return the endereco of this curso participante
	 */
	@AutoEscape
	public String getEndereco();

	/**
	 * Sets the endereco of this curso participante.
	 *
	 * @param endereco the endereco of this curso participante
	 */
	public void setEndereco(String endereco);

	/**
	 * Returns the bairro of this curso participante.
	 *
	 * @return the bairro of this curso participante
	 */
	@AutoEscape
	public String getBairro();

	/**
	 * Sets the bairro of this curso participante.
	 *
	 * @param bairro the bairro of this curso participante
	 */
	public void setBairro(String bairro);

	/**
	 * Returns the cidade of this curso participante.
	 *
	 * @return the cidade of this curso participante
	 */
	@AutoEscape
	public String getCidade();

	/**
	 * Sets the cidade of this curso participante.
	 *
	 * @param cidade the cidade of this curso participante
	 */
	public void setCidade(String cidade);

	/**
	 * Returns the estado of this curso participante.
	 *
	 * @return the estado of this curso participante
	 */
	@AutoEscape
	public String getEstado();

	/**
	 * Sets the estado of this curso participante.
	 *
	 * @param estado the estado of this curso participante
	 */
	public void setEstado(String estado);

	/**
	 * Returns the cep of this curso participante.
	 *
	 * @return the cep of this curso participante
	 */
	@AutoEscape
	public String getCep();

	/**
	 * Sets the cep of this curso participante.
	 *
	 * @param cep the cep of this curso participante
	 */
	public void setCep(String cep);

	/**
	 * Returns the valor pago of this curso participante.
	 *
	 * @return the valor pago of this curso participante
	 */
	@AutoEscape
	public String getValorPago();

	/**
	 * Sets the valor pago of this curso participante.
	 *
	 * @param valorPago the valor pago of this curso participante
	 */
	public void setValorPago(String valorPago);

	/**
	 * Returns the expectativa curso of this curso participante.
	 *
	 * @return the expectativa curso of this curso participante
	 */
	@AutoEscape
	public String getExpectativaCurso();

	/**
	 * Sets the expectativa curso of this curso participante.
	 *
	 * @param expectativaCurso the expectativa curso of this curso participante
	 */
	public void setExpectativaCurso(String expectativaCurso);

	/**
	 * Returns the observacao of this curso participante.
	 *
	 * @return the observacao of this curso participante
	 */
	@AutoEscape
	public String getObservacao();

	/**
	 * Sets the observacao of this curso participante.
	 *
	 * @param observacao the observacao of this curso participante
	 */
	public void setObservacao(String observacao);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		br.com.cnf.curso.inscricao.model.CursoParticipante cursoParticipante);

	@Override
	public int hashCode();

	@Override
	public CacheModel<br.com.cnf.curso.inscricao.model.CursoParticipante> toCacheModel();

	@Override
	public br.com.cnf.curso.inscricao.model.CursoParticipante toEscapedModel();

	@Override
	public br.com.cnf.curso.inscricao.model.CursoParticipante toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}