/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package br.com.cnf.curso.inscricao.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CursoInscricao service. Represents a row in the &quot;cnf_CursoInscricao&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link br.com.cnf.curso.inscricao.model.impl.CursoInscricaoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link br.com.cnf.curso.inscricao.model.impl.CursoInscricaoImpl}.
 * </p>
 *
 * @author SEA
 * @see CursoInscricao
 * @see br.com.cnf.curso.inscricao.model.impl.CursoInscricaoImpl
 * @see br.com.cnf.curso.inscricao.model.impl.CursoInscricaoModelImpl
 * @generated
 */
public interface CursoInscricaoModel extends BaseModel<CursoInscricao> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a curso inscricao model instance should use the {@link CursoInscricao} interface instead.
	 */

	/**
	 * Returns the primary key of this curso inscricao.
	 *
	 * @return the primary key of this curso inscricao
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this curso inscricao.
	 *
	 * @param primaryKey the primary key of this curso inscricao
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the inscricao ID of this curso inscricao.
	 *
	 * @return the inscricao ID of this curso inscricao
	 */
	public long getInscricaoId();

	/**
	 * Sets the inscricao ID of this curso inscricao.
	 *
	 * @param inscricaoId the inscricao ID of this curso inscricao
	 */
	public void setInscricaoId(long inscricaoId);

	/**
	 * Returns the company ID of this curso inscricao.
	 *
	 * @return the company ID of this curso inscricao
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this curso inscricao.
	 *
	 * @param companyId the company ID of this curso inscricao
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this curso inscricao.
	 *
	 * @return the group ID of this curso inscricao
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this curso inscricao.
	 *
	 * @param groupId the group ID of this curso inscricao
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user create ID of this curso inscricao.
	 *
	 * @return the user create ID of this curso inscricao
	 */
	public long getUserCreateId();

	/**
	 * Sets the user create ID of this curso inscricao.
	 *
	 * @param userCreateId the user create ID of this curso inscricao
	 */
	public void setUserCreateId(long userCreateId);

	/**
	 * Returns the user create name of this curso inscricao.
	 *
	 * @return the user create name of this curso inscricao
	 */
	@AutoEscape
	public String getUserCreateName();

	/**
	 * Sets the user create name of this curso inscricao.
	 *
	 * @param userCreateName the user create name of this curso inscricao
	 */
	public void setUserCreateName(String userCreateName);

	/**
	 * Returns the user modified ID of this curso inscricao.
	 *
	 * @return the user modified ID of this curso inscricao
	 */
	public long getUserModifiedId();

	/**
	 * Sets the user modified ID of this curso inscricao.
	 *
	 * @param userModifiedId the user modified ID of this curso inscricao
	 */
	public void setUserModifiedId(long userModifiedId);

	/**
	 * Returns the user modified name of this curso inscricao.
	 *
	 * @return the user modified name of this curso inscricao
	 */
	@AutoEscape
	public String getUserModifiedName();

	/**
	 * Sets the user modified name of this curso inscricao.
	 *
	 * @param userModifiedName the user modified name of this curso inscricao
	 */
	public void setUserModifiedName(String userModifiedName);

	/**
	 * Returns the create date of this curso inscricao.
	 *
	 * @return the create date of this curso inscricao
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this curso inscricao.
	 *
	 * @param createDate the create date of this curso inscricao
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this curso inscricao.
	 *
	 * @return the modified date of this curso inscricao
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this curso inscricao.
	 *
	 * @param modifiedDate the modified date of this curso inscricao
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the curso ID of this curso inscricao.
	 *
	 * @return the curso ID of this curso inscricao
	 */
	public long getCursoId();

	/**
	 * Sets the curso ID of this curso inscricao.
	 *
	 * @param cursoId the curso ID of this curso inscricao
	 */
	public void setCursoId(long cursoId);

	/**
	 * Returns the curso nome of this curso inscricao.
	 *
	 * @return the curso nome of this curso inscricao
	 */
	@AutoEscape
	public String getCursoNome();

	/**
	 * Sets the curso nome of this curso inscricao.
	 *
	 * @param cursoNome the curso nome of this curso inscricao
	 */
	public void setCursoNome(String cursoNome);

	/**
	 * Returns the curso data of this curso inscricao.
	 *
	 * @return the curso data of this curso inscricao
	 */
	@AutoEscape
	public String getCursoData();

	/**
	 * Sets the curso data of this curso inscricao.
	 *
	 * @param cursoData the curso data of this curso inscricao
	 */
	public void setCursoData(String cursoData);

	/**
	 * Returns the curso horario of this curso inscricao.
	 *
	 * @return the curso horario of this curso inscricao
	 */
	@AutoEscape
	public String getCursoHorario();

	/**
	 * Sets the curso horario of this curso inscricao.
	 *
	 * @param cursoHorario the curso horario of this curso inscricao
	 */
	public void setCursoHorario(String cursoHorario);

	/**
	 * Returns the curso local of this curso inscricao.
	 *
	 * @return the curso local of this curso inscricao
	 */
	@AutoEscape
	public String getCursoLocal();

	/**
	 * Sets the curso local of this curso inscricao.
	 *
	 * @param cursoLocal the curso local of this curso inscricao
	 */
	public void setCursoLocal(String cursoLocal);

	/**
	 * Returns the preco of this curso inscricao.
	 *
	 * @return the preco of this curso inscricao
	 */
	@AutoEscape
	public String getPreco();

	/**
	 * Sets the preco of this curso inscricao.
	 *
	 * @param preco the preco of this curso inscricao
	 */
	public void setPreco(String preco);

	/**
	 * Returns the preco convenio of this curso inscricao.
	 *
	 * @return the preco convenio of this curso inscricao
	 */
	@AutoEscape
	public String getPrecoConvenio();

	/**
	 * Sets the preco convenio of this curso inscricao.
	 *
	 * @param precoConvenio the preco convenio of this curso inscricao
	 */
	public void setPrecoConvenio(String precoConvenio);

	/**
	 * Returns the preco associado of this curso inscricao.
	 *
	 * @return the preco associado of this curso inscricao
	 */
	@AutoEscape
	public String getPrecoAssociado();

	/**
	 * Sets the preco associado of this curso inscricao.
	 *
	 * @param precoAssociado the preco associado of this curso inscricao
	 */
	public void setPrecoAssociado(String precoAssociado);

	/**
	 * Returns the tipo fisica juridica of this curso inscricao.
	 *
	 * @return the tipo fisica juridica of this curso inscricao
	 */
	@AutoEscape
	public String getTipoFisicaJuridica();

	/**
	 * Sets the tipo fisica juridica of this curso inscricao.
	 *
	 * @param tipoFisicaJuridica the tipo fisica juridica of this curso inscricao
	 */
	public void setTipoFisicaJuridica(String tipoFisicaJuridica);

	/**
	 * Returns the cpf cnpj of this curso inscricao.
	 *
	 * @return the cpf cnpj of this curso inscricao
	 */
	@AutoEscape
	public String getCpfCnpj();

	/**
	 * Sets the cpf cnpj of this curso inscricao.
	 *
	 * @param cpfCnpj the cpf cnpj of this curso inscricao
	 */
	public void setCpfCnpj(String cpfCnpj);

	/**
	 * Returns the nome responsavel of this curso inscricao.
	 *
	 * @return the nome responsavel of this curso inscricao
	 */
	@AutoEscape
	public String getNomeResponsavel();

	/**
	 * Sets the nome responsavel of this curso inscricao.
	 *
	 * @param nomeResponsavel the nome responsavel of this curso inscricao
	 */
	public void setNomeResponsavel(String nomeResponsavel);

	/**
	 * Returns the email principal of this curso inscricao.
	 *
	 * @return the email principal of this curso inscricao
	 */
	@AutoEscape
	public String getEmailPrincipal();

	/**
	 * Sets the email principal of this curso inscricao.
	 *
	 * @param emailPrincipal the email principal of this curso inscricao
	 */
	public void setEmailPrincipal(String emailPrincipal);

	/**
	 * Returns the ddd telefone comercial of this curso inscricao.
	 *
	 * @return the ddd telefone comercial of this curso inscricao
	 */
	@AutoEscape
	public String getDddTelefoneComercial();

	/**
	 * Sets the ddd telefone comercial of this curso inscricao.
	 *
	 * @param dddTelefoneComercial the ddd telefone comercial of this curso inscricao
	 */
	public void setDddTelefoneComercial(String dddTelefoneComercial);

	/**
	 * Returns the telefone comercial of this curso inscricao.
	 *
	 * @return the telefone comercial of this curso inscricao
	 */
	@AutoEscape
	public String getTelefoneComercial();

	/**
	 * Sets the telefone comercial of this curso inscricao.
	 *
	 * @param telefoneComercial the telefone comercial of this curso inscricao
	 */
	public void setTelefoneComercial(String telefoneComercial);

	/**
	 * Returns the sexo of this curso inscricao.
	 *
	 * @return the sexo of this curso inscricao
	 */
	@AutoEscape
	public String getSexo();

	/**
	 * Sets the sexo of this curso inscricao.
	 *
	 * @param sexo the sexo of this curso inscricao
	 */
	public void setSexo(String sexo);

	/**
	 * Returns the cadastro finalizado of this curso inscricao.
	 *
	 * @return the cadastro finalizado of this curso inscricao
	 */
	public boolean getCadastroFinalizado();

	/**
	 * Returns <code>true</code> if this curso inscricao is cadastro finalizado.
	 *
	 * @return <code>true</code> if this curso inscricao is cadastro finalizado; <code>false</code> otherwise
	 */
	public boolean isCadastroFinalizado();

	/**
	 * Sets whether this curso inscricao is cadastro finalizado.
	 *
	 * @param cadastroFinalizado the cadastro finalizado of this curso inscricao
	 */
	public void setCadastroFinalizado(boolean cadastroFinalizado);

	/**
	 * Returns the forma pagamento of this curso inscricao.
	 *
	 * @return the forma pagamento of this curso inscricao
	 */
	@AutoEscape
	public String getFormaPagamento();

	/**
	 * Sets the forma pagamento of this curso inscricao.
	 *
	 * @param formaPagamento the forma pagamento of this curso inscricao
	 */
	public void setFormaPagamento(String formaPagamento);

	/**
	 * Returns the numero cartao of this curso inscricao.
	 *
	 * @return the numero cartao of this curso inscricao
	 */
	@AutoEscape
	public String getNumeroCartao();

	/**
	 * Sets the numero cartao of this curso inscricao.
	 *
	 * @param numeroCartao the numero cartao of this curso inscricao
	 */
	public void setNumeroCartao(String numeroCartao);

	/**
	 * Returns the validade cartao mes of this curso inscricao.
	 *
	 * @return the validade cartao mes of this curso inscricao
	 */
	public int getValidadeCartaoMes();

	/**
	 * Sets the validade cartao mes of this curso inscricao.
	 *
	 * @param validadeCartaoMes the validade cartao mes of this curso inscricao
	 */
	public void setValidadeCartaoMes(int validadeCartaoMes);

	/**
	 * Returns the validade cartao ano of this curso inscricao.
	 *
	 * @return the validade cartao ano of this curso inscricao
	 */
	public int getValidadeCartaoAno();

	/**
	 * Sets the validade cartao ano of this curso inscricao.
	 *
	 * @param validadeCartaoAno the validade cartao ano of this curso inscricao
	 */
	public void setValidadeCartaoAno(int validadeCartaoAno);

	/**
	 * Returns the nome titular cartao of this curso inscricao.
	 *
	 * @return the nome titular cartao of this curso inscricao
	 */
	@AutoEscape
	public String getNomeTitularCartao();

	/**
	 * Sets the nome titular cartao of this curso inscricao.
	 *
	 * @param nomeTitularCartao the nome titular cartao of this curso inscricao
	 */
	public void setNomeTitularCartao(String nomeTitularCartao);

	/**
	 * Returns the codigo seguranca cartao of this curso inscricao.
	 *
	 * @return the codigo seguranca cartao of this curso inscricao
	 */
	@AutoEscape
	public String getCodigoSegurancaCartao();

	/**
	 * Sets the codigo seguranca cartao of this curso inscricao.
	 *
	 * @param codigoSegurancaCartao the codigo seguranca cartao of this curso inscricao
	 */
	public void setCodigoSegurancaCartao(String codigoSegurancaCartao);

	/**
	 * Returns the status moeda digital of this curso inscricao.
	 *
	 * @return the status moeda digital of this curso inscricao
	 */
	@AutoEscape
	public String getStatusMoedaDigital();

	/**
	 * Sets the status moeda digital of this curso inscricao.
	 *
	 * @param statusMoedaDigital the status moeda digital of this curso inscricao
	 */
	public void setStatusMoedaDigital(String statusMoedaDigital);

	/**
	 * Returns the quantidade parcelas of this curso inscricao.
	 *
	 * @return the quantidade parcelas of this curso inscricao
	 */
	public int getQuantidadeParcelas();

	/**
	 * Sets the quantidade parcelas of this curso inscricao.
	 *
	 * @param quantidadeParcelas the quantidade parcelas of this curso inscricao
	 */
	public void setQuantidadeParcelas(int quantidadeParcelas);

	/**
	 * Returns the valor total of this curso inscricao.
	 *
	 * @return the valor total of this curso inscricao
	 */
	public double getValorTotal();

	/**
	 * Sets the valor total of this curso inscricao.
	 *
	 * @param valorTotal the valor total of this curso inscricao
	 */
	public void setValorTotal(double valorTotal);

	/**
	 * Returns the moeda digital pedido of this curso inscricao.
	 *
	 * @return the moeda digital pedido of this curso inscricao
	 */
	@AutoEscape
	public String getMoedaDigitalPedido();

	/**
	 * Sets the moeda digital pedido of this curso inscricao.
	 *
	 * @param moedaDigitalPedido the moeda digital pedido of this curso inscricao
	 */
	public void setMoedaDigitalPedido(String moedaDigitalPedido);

	/**
	 * Returns the data inicio of this curso inscricao.
	 *
	 * @return the data inicio of this curso inscricao
	 */
	public Date getDataInicio();

	/**
	 * Sets the data inicio of this curso inscricao.
	 *
	 * @param dataInicio the data inicio of this curso inscricao
	 */
	public void setDataInicio(Date dataInicio);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		br.com.cnf.curso.inscricao.model.CursoInscricao cursoInscricao);

	@Override
	public int hashCode();

	@Override
	public CacheModel<br.com.cnf.curso.inscricao.model.CursoInscricao> toCacheModel();

	@Override
	public br.com.cnf.curso.inscricao.model.CursoInscricao toEscapedModel();

	@Override
	public br.com.cnf.curso.inscricao.model.CursoInscricao toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}