/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package br.com.cnf.curso.inscricao.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the CursoInscricaoCnpj service. Represents a row in the &quot;cnf_CursoInscricaoCnpj&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link br.com.cnf.curso.inscricao.model.impl.CursoInscricaoCnpjModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link br.com.cnf.curso.inscricao.model.impl.CursoInscricaoCnpjImpl}.
 * </p>
 *
 * @author SEA
 * @see CursoInscricaoCnpj
 * @see br.com.cnf.curso.inscricao.model.impl.CursoInscricaoCnpjImpl
 * @see br.com.cnf.curso.inscricao.model.impl.CursoInscricaoCnpjModelImpl
 * @generated
 */
public interface CursoInscricaoCnpjModel extends BaseModel<CursoInscricaoCnpj> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a curso inscricao cnpj model instance should use the {@link CursoInscricaoCnpj} interface instead.
	 */

	/**
	 * Returns the primary key of this curso inscricao cnpj.
	 *
	 * @return the primary key of this curso inscricao cnpj
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this curso inscricao cnpj.
	 *
	 * @param primaryKey the primary key of this curso inscricao cnpj
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the inscricao cnpj ID of this curso inscricao cnpj.
	 *
	 * @return the inscricao cnpj ID of this curso inscricao cnpj
	 */
	public long getInscricaoCnpjId();

	/**
	 * Sets the inscricao cnpj ID of this curso inscricao cnpj.
	 *
	 * @param inscricaoCnpjId the inscricao cnpj ID of this curso inscricao cnpj
	 */
	public void setInscricaoCnpjId(long inscricaoCnpjId);

	/**
	 * Returns the inscricao ID of this curso inscricao cnpj.
	 *
	 * @return the inscricao ID of this curso inscricao cnpj
	 */
	public long getInscricaoId();

	/**
	 * Sets the inscricao ID of this curso inscricao cnpj.
	 *
	 * @param inscricaoId the inscricao ID of this curso inscricao cnpj
	 */
	public void setInscricaoId(long inscricaoId);

	/**
	 * Returns the razao social of this curso inscricao cnpj.
	 *
	 * @return the razao social of this curso inscricao cnpj
	 */
	@AutoEscape
	public String getRazaoSocial();

	/**
	 * Sets the razao social of this curso inscricao cnpj.
	 *
	 * @param razaoSocial the razao social of this curso inscricao cnpj
	 */
	public void setRazaoSocial(String razaoSocial);

	/**
	 * Returns the nome fantasia of this curso inscricao cnpj.
	 *
	 * @return the nome fantasia of this curso inscricao cnpj
	 */
	@AutoEscape
	public String getNomeFantasia();

	/**
	 * Sets the nome fantasia of this curso inscricao cnpj.
	 *
	 * @param nomeFantasia the nome fantasia of this curso inscricao cnpj
	 */
	public void setNomeFantasia(String nomeFantasia);

	/**
	 * Returns the inscricao estadual of this curso inscricao cnpj.
	 *
	 * @return the inscricao estadual of this curso inscricao cnpj
	 */
	@AutoEscape
	public String getInscricaoEstadual();

	/**
	 * Sets the inscricao estadual of this curso inscricao cnpj.
	 *
	 * @param inscricaoEstadual the inscricao estadual of this curso inscricao cnpj
	 */
	public void setInscricaoEstadual(String inscricaoEstadual);

	/**
	 * Returns the endereco of this curso inscricao cnpj.
	 *
	 * @return the endereco of this curso inscricao cnpj
	 */
	@AutoEscape
	public String getEndereco();

	/**
	 * Sets the endereco of this curso inscricao cnpj.
	 *
	 * @param endereco the endereco of this curso inscricao cnpj
	 */
	public void setEndereco(String endereco);

	/**
	 * Returns the bairro of this curso inscricao cnpj.
	 *
	 * @return the bairro of this curso inscricao cnpj
	 */
	@AutoEscape
	public String getBairro();

	/**
	 * Sets the bairro of this curso inscricao cnpj.
	 *
	 * @param bairro the bairro of this curso inscricao cnpj
	 */
	public void setBairro(String bairro);

	/**
	 * Returns the cidade of this curso inscricao cnpj.
	 *
	 * @return the cidade of this curso inscricao cnpj
	 */
	@AutoEscape
	public String getCidade();

	/**
	 * Sets the cidade of this curso inscricao cnpj.
	 *
	 * @param cidade the cidade of this curso inscricao cnpj
	 */
	public void setCidade(String cidade);

	/**
	 * Returns the estado of this curso inscricao cnpj.
	 *
	 * @return the estado of this curso inscricao cnpj
	 */
	@AutoEscape
	public String getEstado();

	/**
	 * Sets the estado of this curso inscricao cnpj.
	 *
	 * @param estado the estado of this curso inscricao cnpj
	 */
	public void setEstado(String estado);

	/**
	 * Returns the cep of this curso inscricao cnpj.
	 *
	 * @return the cep of this curso inscricao cnpj
	 */
	@AutoEscape
	public String getCep();

	/**
	 * Sets the cep of this curso inscricao cnpj.
	 *
	 * @param cep the cep of this curso inscricao cnpj
	 */
	public void setCep(String cep);

	/**
	 * Returns the ddd telefone of this curso inscricao cnpj.
	 *
	 * @return the ddd telefone of this curso inscricao cnpj
	 */
	@AutoEscape
	public String getDddTelefone();

	/**
	 * Sets the ddd telefone of this curso inscricao cnpj.
	 *
	 * @param dddTelefone the ddd telefone of this curso inscricao cnpj
	 */
	public void setDddTelefone(String dddTelefone);

	/**
	 * Returns the telefone of this curso inscricao cnpj.
	 *
	 * @return the telefone of this curso inscricao cnpj
	 */
	@AutoEscape
	public String getTelefone();

	/**
	 * Sets the telefone of this curso inscricao cnpj.
	 *
	 * @param telefone the telefone of this curso inscricao cnpj
	 */
	public void setTelefone(String telefone);

	/**
	 * Returns the nf nome of this curso inscricao cnpj.
	 *
	 * @return the nf nome of this curso inscricao cnpj
	 */
	@AutoEscape
	public String getNfNome();

	/**
	 * Sets the nf nome of this curso inscricao cnpj.
	 *
	 * @param nfNome the nf nome of this curso inscricao cnpj
	 */
	public void setNfNome(String nfNome);

	/**
	 * Returns the nf departamento of this curso inscricao cnpj.
	 *
	 * @return the nf departamento of this curso inscricao cnpj
	 */
	@AutoEscape
	public String getNfDepartamento();

	/**
	 * Sets the nf departamento of this curso inscricao cnpj.
	 *
	 * @param nfDepartamento the nf departamento of this curso inscricao cnpj
	 */
	public void setNfDepartamento(String nfDepartamento);

	/**
	 * Returns the nf email of this curso inscricao cnpj.
	 *
	 * @return the nf email of this curso inscricao cnpj
	 */
	@AutoEscape
	public String getNfEmail();

	/**
	 * Sets the nf email of this curso inscricao cnpj.
	 *
	 * @param nfEmail the nf email of this curso inscricao cnpj
	 */
	public void setNfEmail(String nfEmail);

	/**
	 * Returns the nf ddd telefone of this curso inscricao cnpj.
	 *
	 * @return the nf ddd telefone of this curso inscricao cnpj
	 */
	@AutoEscape
	public String getNfDddTelefone();

	/**
	 * Sets the nf ddd telefone of this curso inscricao cnpj.
	 *
	 * @param nfDddTelefone the nf ddd telefone of this curso inscricao cnpj
	 */
	public void setNfDddTelefone(String nfDddTelefone);

	/**
	 * Returns the nf telefone of this curso inscricao cnpj.
	 *
	 * @return the nf telefone of this curso inscricao cnpj
	 */
	@AutoEscape
	public String getNfTelefone();

	/**
	 * Sets the nf telefone of this curso inscricao cnpj.
	 *
	 * @param nfTelefone the nf telefone of this curso inscricao cnpj
	 */
	public void setNfTelefone(String nfTelefone);

	/**
	 * Returns the observacao of this curso inscricao cnpj.
	 *
	 * @return the observacao of this curso inscricao cnpj
	 */
	@AutoEscape
	public String getObservacao();

	/**
	 * Sets the observacao of this curso inscricao cnpj.
	 *
	 * @param observacao the observacao of this curso inscricao cnpj
	 */
	public void setObservacao(String observacao);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		br.com.cnf.curso.inscricao.model.CursoInscricaoCnpj cursoInscricaoCnpj);

	@Override
	public int hashCode();

	@Override
	public CacheModel<br.com.cnf.curso.inscricao.model.CursoInscricaoCnpj> toCacheModel();

	@Override
	public br.com.cnf.curso.inscricao.model.CursoInscricaoCnpj toEscapedModel();

	@Override
	public br.com.cnf.curso.inscricao.model.CursoInscricaoCnpj toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}